#!/bin/bash

    sed 's/\?//g' |
    #remove ?

    sed 's/<u>//g' |
    #remove <u>

    sed 's/<\/u>//g' | 
    #remove </u>

    sed "s/\`/\'/g" |
    #replace ` with '

    tr '[:upper:]' '[:lower:]' |
    #change everything to lowercase
    
    sed "s/^\s*<td[^>]*>\([\'pkmnwlhaeiou ]*\)<\/td>\s*$/\1/g" |
    #replace ‘A<tdX>W</td>Z’ with W

    sed 's/^[< ].*$//g' |
    #deletes all the english words

    sed 's/\s/\n/g' |
    #separate words into different lines

    tr -s '\n' |
    #delete all the extra empty lines

    sed '/maui/,/<br>/d' |
    #delete the extra english comments at the end

    sort -u
    #sort the text and remove duplicates
